### ISSUE TITLE
Add ability to transform a set of vertices

### ISSUE THREAD

**Issue by pbardea** [calder-gl/calder#14]
- [ ] Scaling
- [ ] Translation
- [ ] Rotation

**Comment by tammy** [comment]
Requesting for comments 😄 
--

Edit: 
- changed origin to hold_point for Scaling
- changed scaling factor to translation unit under Translation

--
### Scaling
```
/**
 * scale
 * @param object - object to be transformed
 * @param scale - scaling factor
 * @param hold_point - point to scale from, origin of scaling vector
 * @param pull_point - point that along with origin determines the scaling vector direction
 */
Transform.scale(WorkingGeometry object, float scale, vec3 hold_point, vec3 pull_point)
```

### Translation
```
/**
 * translate
 * @param object - object to be transformed
 * @param x - x-axis translation unit
 * @param y - y-axis translation unit
 * @param z - z-axis translation unit
 */
Transform.translate(WorkingGeometry object, float x, float y, float z);
```
### Rotation
```
/**
 * rotate
 * @param object - object to be transformed
 * @param axis - axis of rotation defined by two points
 * @param degrees - amount to rotate
 */
struct Axis = {
  vec3 origin;
  vec3 end;
}
Transform.rotate(WorkingGeometry object, Axis axis, float degrees);
```

**Comment by pbardea** [comment]
## Scaling
If we're going with the "pull point" analogy, does having a "hold point" make sense rather than an "origin"?

## Translation
For the translate docstring, it refers to "scaling factor", would it make more sense to have a translation amount instead?

## Rotation
For the rotation, it seems to me that you can rotate it along more than one axis right? Like if I grab a vector I can rotate it along any axis. May be easier to whiteboard this. May be easier to have a destination vector instead that the `axis` vector should line up with.
Edit: the rotation is about the axis. Ignore the above comment.

**Comment by davepagurek** [comment]
I think a hold point still makes sense in this context.

Also, what do you guys think of using an object as the parameters for functions like these so that you can see what each parameter name is? e.g.
```typescript
// Definition
Transform.scale = function({object, hold, pull, scale}: {object: WorkingGeometry, hold: vec3, pull: vec3, scale: number}) {
  // ...
}

// Usage
Transform.scale({object: my_object, hold: vec3.create(...), pull: vec3.create(...), scale: 2});
```

I think once we start having multiple points/vectors being passed in, it's maybe easier to read/write this way than having to remember the positional argument order.

Other question that I dont have an opinion on but we should decide: do we want these operations to be member functions of `WorkingGeometry ` and return a new `WorkingGeometry`, or non-member functions that take one in?

**Comment by pbardea** [comment]
> Also, what do you guys think of using an object as the parameters for functions like these so that you can see what each parameter name is?

I like the idea of named parameters. If we do this, we should make sure that we keep it consistent throughout Calder. My main concern is that I'm not sure how standard this practice is and how that contributes to the learning curve of learning Calder. Do you have any thoughts on this?

Side note: is the ":" in `function({object, hold: pull, scale}:` a typo? If not, then I'm having a hard time wrapping my head around what's going on here exactly...

> Other question that I dont have an opinion on but we should decide: do we want these operations to be member functions of WorkingGeometry and return a new WorkingGeometry, or non-member functions that take one in?

I think that OOP works well when thinking about real objects, so I would vote for the operations to be member functions of `WorkingGeomtery`.

**Comment by davepagurek** [comment]
oops yeah that's a typo! edited

**Comment by davepagurek** [comment]
A notable library that uses the parameters object pattern is d3, e.g. https://github.com/d3/d3-shape/blob/master/README.md#arc

Although another approach (which you see right after the object parameters) is chaining setters. That can also be good, although it's nice being able to guarantee that you can't leave the object in a bad state by passing in all the params at once

**Comment by tammy** [comment]
I prefer the parameters object pattern over the chaining setters for the reason you described :) I've found that in general having named parameters automatically helps with self-documentation.
