### ISSUE TITLE
Create interface for rendering geometry

### ISSUE THREAD

**Issue by davepagurek** [calder-gl/calder#17]
We should bake geometric data into *only* what's needed for rendering and armatures after we have finished creating it. This should probably include some of the things in the current `RenderObject` interface (vertices and indices), and also any control points we want to "export" for use in armatures.

**Comment by armcburney** [comment]
> bake geometric data

<img width="258" alt="screen shot 2018-05-03 at 11 58 45 am" src="https://user-images.githubusercontent.com/8942499/39588220-5e53e11a-4ec9-11e8-9342-ac7b93370867.png">
