### ISSUE TITLE
Create interface for geometry as it is being edited

### ISSUE THREAD

**Issue by davepagurek** [calder-gl/calder#18]
As geometry is being edited, we should keep it in a better format than just vertices/indices/normals. Some considerations:
- When editing, surface normals probably make more sense than vertex normals (e.g. after carving out part of a shape, what should the normal be along the edge? it's maybe impossible to say)
- We may want to store polygons instead of vertices, and generate the vertex/index array after we're done editing
  - If we do polygons, should we use quads instead of triangles to better support subdivisions later?

**Comment by pbardea** [comment]
Random thought which may be relevant here: I think that it may be useful to have this other representation and have a method to retrieve the verticies/normals/etc... which can be cached to ensure we don't do duplicate work.

Side note: This seems to overlap quite a bit w/ #13 (the shape part of the "shape->vertices"), @abhimadan do you think that this is a separate issue or were you planning on tackling that as well?
