### ISSUE TITLE
Create public interface for creating armatures and attaching geometry

### ISSUE THREAD

**Issue by davepagurek** [calder-gl/calder#35]
This will probably include creating control points for armature nodes, and making a way to specify a base bone shape ("shape" being a default set of control points to snap to), instantiate that, and attach other pieces

**Comment by armcburney** [comment]
Is this blocked on the Geometry stuff?

**Comment by davepagurek** [comment]
Nah this should be fine

**Comment by armcburney** [comment]
ay lmao
