### ISSUE TITLE
Basic editor

### ISSUE THREAD

**Issue by davepagurek** [calder-gl/calder#69]
For a demo we want a really basic editor to use:

- Textbox on the left (no need for highlighting or anything, just monospace)
- Canvas to the right
- Button to rerender

Nice-to-haves that aren't necessary (feel free to make new issues for them after the initial part is done):
- Rerendering starts with the same random seed every time unless we press a "randomize" button to reset it (Made a separate issue https://github.com/calder-gl/calder/issues/71 to facilitate this)
- Save code to local storage

**Comment by armcburney** [comment]
Yo, imma do this one if it's gucci

**Comment by davepagurek** [comment]
Updated to add local storage as a nice-to-have. Basically we'll just see how far we can get I guess?

**Comment by armcburney** [comment]
Working on the editor in the [`playground`](https://github.com/calder-gl/playground) repo.
