### ISSUE TITLE
Look into how mouse position stuff works (relating back to 3D on GPU) 

### ISSUE THREAD

**Issue by pbardea** [calder-gl/calder#8]

**Comment by davepagurek** [comment]
Seems like what we'll want to do is assign a value to each object (e.g. a unique colour), and then render to an offscreen buffer that flat shaded colour. Then, when we want to look up the object at a coordinate, we find the colour of that pixel and look up the corresponding object

**Comment by pbardea** [comment]
Seems like a good start, going to close this for now and we can refer to it later.
