### ISSUE TITLE
Create helpers for common operations in client code utilizing Calder, and provide a way to create `mat4`, vec3`s, etc. using Calder

### ISSUE THREAD

**Issue by armcburney** [calder-gl/calder#80]
Rather than having a user import libraries such as `gl-matrix` (for the `mat4`, `quat`, `vec3`, etc.) or `lodash` (for `flatMap`) in their code using the calder library, we should try to abstract as much of this as we can, so the user would only need to include our library.

Ideally, all the code in the `/examples` folder would just utilize our library, and not use external libraires.

For a bit more context, please see [here](https://github.com/calder-gl/calder/pull/74#discussion_r194232401).

**Comment by davepagurek** [comment]
I think a lot of this is covered by these issues:
https://github.com/calder-gl/calder/issues/66 (add colour to geometry api so you dont map it yourself)
https://github.com/calder-gl/calder/issues/53 (represent colour differently than just a vec3)
https://github.com/calder-gl/calder/issues/48 (use a different public facing API for vectors)

**Comment by armcburney** [comment]
I have PRs up for issues #66 (#86) and #48 (#87), and we merged the PR for issue #53 (#82). Once these two PRs are merged, I'll close this issue :partyparrot:.
