### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by armcburney** [calder-gl/calder#9]
### Changes
- Add continuous integration for calder (CircleCI)

### Checks
- [x] Linter check
- [x] Tests pass

**Comment by pbardea** [comment]
@AndrewMcBurney Can you also include what this is blocked on when adding the blocked tag? :) Thanks!

**Comment by davepagurek** [comment]
Closing this because CI is running again now (it got messed up after the renames, circleci stopped running new builds after that)
